id: PYSEC-2020-32
details: An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7.
  Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly
  URL encoded, leading to a possibility of an XSS attack.
affected:
- package:
    name: django
    ecosystem: PyPI
    purl: pkg:pypi:django
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: '2.2'
    - fixed: 2.2.13
    - introduced: '3.0'
    - fixed: 3.0.7
  versions:
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.2.4
  - 2.2.5
  - 2.2.6
  - 2.2.7
  - 2.2.8
  - 2.2.9
  - 2.2.10
  - 2.2.11
  - 2.2.12
  - '3.0'
  - 3.0.1
  - 3.0.2
  - 3.0.3
  - 3.0.4
  - 3.0.5
  - 3.0.6
references:
- type: ARTICLE
  url: https://www.djangoproject.com/weblog/2020/jun/03/security-releases/
- type: WEB
  url: https://groups.google.com/forum/#!msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ
- type: WEB
  url: https://docs.djangoproject.com/en/3.0/releases/security/
- type: WEB
  url: https://usn.ubuntu.com/4381-1/
- type: WEB
  url: https://usn.ubuntu.com/4381-2/
- type: ADVISORY
  url: https://security.netapp.com/advisory/ntap-20200611-0002/
- type: ADVISORY
  url: https://www.debian.org/security/2020/dsa-4705
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/
- type: WEB
  url: https://www.oracle.com/security-alerts/cpujan2021.html
- type: ADVISORY
  url: https://github.com/advisories/GHSA-2m34-jcjv-45xf
aliases:
- CVE-2020-13596
- GHSA-2m34-jcjv-45xf
modified: '2021-01-20T15:15:00Z'
published: '2020-06-03T14:15:00Z'
