id: PYSEC-2021-59
details: The urllib3 library 1.26.x before 1.26.4 for Python omits SSL certificate
  validation in some cases involving HTTPS to HTTPS proxies. The initial connection
  to the HTTPS proxy (if an SSLContext isn't given via proxy_config) doesn't verify
  the hostname of the certificate. This means certificates for different servers that
  still validate properly with the default urllib3 SSLContext will be silently accepted.
affected:
- package:
    name: urllib3
    ecosystem: PyPI
    purl: pkg:pypi:urllib3
  ranges:
  - type: GIT
    repo: https://github.com/urllib3/urllib3
    events:
    - introduced: "0"
    - fixed: 8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0
  - type: ECOSYSTEM
    events:
    - introduced: 1.26.0
    - fixed: 1.26.4
  versions:
  - 1.26.0
  - 1.26.1
  - 1.26.2
  - 1.26.3
references:
- type: WEB
  url: https://github.com/urllib3/urllib3/commits/main
- type: PACKAGE
  url: https://pypi.org/project/urllib3/1.26.4/
- type: FIX
  url: https://github.com/urllib3/urllib3/commit/8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0
- type: ADVISORY
  url: https://github.com/urllib3/urllib3/security/advisories/GHSA-5phf-pp7p-vc2r
aliases:
- CVE-2021-28363
- GHSA-5phf-pp7p-vc2r
modified: "2021-03-23T16:47:00Z"
published: "2021-03-15T18:15:00Z"
