affected:
- package:
    ecosystem: PyPI
    name: tensorflow-cpu
    purl: pkg:pypi:tensorflow-cpu
  ranges:
  - events:
    - introduced: '0'
    - fixed: 44b7f486c0143f68b56c34e2d01e146ee445134a
    repo: https://github.com/tensorflow/tensorflow
    type: GIT
  - events:
    - introduced: '0'
    - fixed: 2.2.0rc0
    - introduced: 2.2.0
    - fixed: 2.3.0rc0
    - introduced: 2.3.0
    - fixed: 2.3.4
    - introduced: 2.4.0
    - fixed: 2.4.3
    type: ECOSYSTEM
aliases:
- CVE-2021-29532
- GHSA-j47f-4232-hvv8
details: TensorFlow is an end-to-end open source platform for machine learning. An
  attacker can force accesses outside the bounds of heap allocated arrays by passing
  in invalid tensor values to `tf.raw_ops.RaggedCross`. This is because the implementation(https://github.com/tensorflow/tensorflow/blob/efea03b38fb8d3b81762237dc85e579cc5fc6e87/tensorflow/core/kernels/ragged_cross_op.cc#L456-L487)
  lacks validation for the user supplied arguments. Each of the above branches call
  a helper function after accessing array elements via a `*_list[next_*]` pattern,
  followed by incrementing the `next_*` index. However, as there is no validation
  that the `next_*` values are in the valid range for the corresponding `*_list` arrays,
  this results in heap OOB reads. The fix will be included in TensorFlow 2.5.0. We
  will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow
  2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.
id: PYSEC-0000-CVE-2021-29532
modified: '2021-08-27T03:22:27.051975Z'
published: '2021-05-14T20:15:00Z'
references:
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/44b7f486c0143f68b56c34e2d01e146ee445134a
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-j47f-4232-hvv8
