affected:
- package:
    ecosystem: PyPI
    name: tensorflow-cpu
    purl: pkg:pypi:tensorflow-cpu
  ranges:
  - events:
    - introduced: '0'
    - fixed: b432a38fe0e1b4b904a6c222cbce794c39703e87
    repo: https://github.com/tensorflow/tensorflow
    type: GIT
  - events:
    - introduced: '0'
    - fixed: 2.2.0rc0
    - introduced: 2.2.0
    - fixed: 2.3.0rc0
    - introduced: 2.3.0
    - fixed: 2.3.4
    - introduced: 2.4.0
    - fixed: 2.4.3
    type: ECOSYSTEM
aliases:
- CVE-2021-29533
- GHSA-393f-2jr3-cp69
details: TensorFlow is an end-to-end open source platform for machine learning. An
  attacker can trigger a denial of service via a `CHECK` failure by passing an empty
  image to `tf.raw_ops.DrawBoundingBoxes`. This is because the implementation(https://github.com/tensorflow/tensorflow/blob/ea34a18dc3f5c8d80a40ccca1404f343b5d55f91/tensorflow/core/kernels/image/draw_bounding_box_op.cc#L148-L165)
  uses `CHECK_*` assertions instead of `OP_REQUIRES` to validate user controlled inputs.
  Whereas `OP_REQUIRES` allows returning an error condition back to the user, the
  `CHECK_*` macros result in a crash if the condition is false, similar to `assert`.
  In this case, `height` is 0 from the `images` input. This results in `max_box_row_clamp`
  being negative and the assertion being falsified, followed by aborting program execution.
  The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit
  on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as
  these are also affected and still in supported range.
id: PYSEC-0000-CVE-2021-29533
modified: '2021-08-27T03:22:27.240459Z'
published: '2021-05-14T20:15:00Z'
references:
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-393f-2jr3-cp69
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/b432a38fe0e1b4b904a6c222cbce794c39703e87
