affected:
- package:
    ecosystem: PyPI
    name: tensorflow-cpu
    purl: pkg:pypi:tensorflow-cpu
  ranges:
  - events:
    - introduced: '0'
    - fixed: 4071d8e2f6c45c1955a811fee757ca2adbe462c1
    repo: https://github.com/tensorflow/tensorflow
    type: GIT
  - events:
    - introduced: '0'
    - fixed: 2.2.0rc0
    - introduced: 2.2.0
    - fixed: 2.3.0rc0
    - introduced: 2.3.0
    - fixed: 2.3.4
    - introduced: 2.4.0
    - fixed: 2.4.3
    type: ECOSYSTEM
aliases:
- CVE-2021-29556
- GHSA-fxqh-cfjm-fp93
details: TensorFlow is an end-to-end open source platform for machine learning. An
  attacker can cause a denial of service via a FPE runtime error in `tf.raw_ops.Reverse`.
  This is because the implementation(https://github.com/tensorflow/tensorflow/blob/36229ea9e9451dac14a8b1f4711c435a1d84a594/tensorflow/core/kernels/reverse_op.cc#L75-L76)
  performs a division based on the first dimension of the tensor argument. The fix
  will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow
  2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also
  affected and still in supported range.
id: PYSEC-0000-CVE-2021-29556
modified: '2021-08-27T03:22:31.368222Z'
published: '2021-05-14T20:15:00Z'
references:
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-fxqh-cfjm-fp93
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/4071d8e2f6c45c1955a811fee757ca2adbe462c1
