id: PYSEC-2010-7
details: Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before
  0.5.1 allows remote attackers to cause a denial of service (daemon outage) by establishing
  and then immediately closing a TCP connection, leading to the accept function having
  an unexpected return value of None, a different vulnerability than CVE-2010-3494.
affected:
- package:
    name: pyftpdlib
    ecosystem: PyPI
    purl: pkg:pypi/pyftpdlib
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 0.5.1
  versions:
  - 0.2.0
  - 0.3.0
  - 0.4.0
  - 0.5.0
references:
- type: WEB
  url: http://code.google.com/p/pyftpdlib/source/detail?r=439
- type: WEB
  url: https://bugs.launchpad.net/zodb/+bug/135108
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2010/09/24/3
- type: WEB
  url: http://code.google.com/p/pyftpdlib/issues/detail?id=91
- type: WEB
  url: http://code.google.com/p/pyftpdlib/source/diff?spec=svn439&r=439&format=side&path=/trunk/pyftpdlib/ftpserver.py
- type: WEB
  url: http://bugs.python.org/issue6706
- type: WEB
  url: http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2010/09/09/6
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2010/09/22/3
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2010/09/11/2
- type: ADVISORY
  url: https://github.com/advisories/GHSA-mpg6-rgp4-35rr
aliases:
- CVE-2009-5010
- GHSA-mpg6-rgp4-35rr
modified: "2021-07-05T00:01:24.754790Z"
published: "2010-10-19T20:00:00Z"
