id: PYSEC-0000-CVE-2021-29543
package:
  name: tensorflow
  ecosystem: PyPI
details: TensorFlow is an end-to-end open source platform for machine learning. An
  attacker can trigger a denial of service via a `CHECK`-fail in `tf.raw_ops.CTCGreedyDecoder`.
  This is because the implementation(https://github.com/tensorflow/tensorflow/blob/1615440b17b364b875eb06f43d087381f1460a65/tensorflow/core/kernels/ctc_decoder_ops.cc#L37-L50)
  has a `CHECK_LT` inserted to validate some invariants. When this condition is false,
  the program aborts, instead of returning a valid error to the user. This abnormal
  termination can be weaponized in denial of service attacks. The fix will be included
  in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow
  2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still
  in supported range.
affects:
  ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    fixed: ea3b43e98c32c97b35d52b4c66f9107452ca8fb2
  - type: ECOSYSTEM
    fixed: 2.2.0rc0
  - type: ECOSYSTEM
    introduced: 2.2.0
    fixed: 2.3.0rc0
  - type: ECOSYSTEM
    introduced: 2.3.0
    fixed: 2.3.4
  - type: ECOSYSTEM
    introduced: 2.4.0
    fixed: 2.4.3
references:
- type: WEB
  url: https://github.com/tensorflow/tensorflow/commit/ea3b43e98c32c97b35d52b4c66f9107452ca8fb2
- type: WEB
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-fphq-gw9m-ghrv
aliases:
- CVE-2021-29543
modified: "2021-05-18T16:50:00Z"
published: "2021-05-14T20:15:00Z"
