id: PYSEC-0000-CVE-2021-37654
package:
  name: tensorflow
  ecosystem: PyPI
details: TensorFlow is an end-to-end open source platform for machine learning. In
  affected versions an attacker can trigger a crash via a `CHECK`-fail in debug builds
  of TensorFlow using `tf.raw_ops.ResourceGather` or a read from outside the bounds
  of heap allocated data in the same API in a release build. The [implementation](https://github.com/tensorflow/tensorflow/blob/f24faa153ad31a4b51578f8181d3aaab77a1ddeb/tensorflow/core/kernels/resource_variable_ops.cc#L660-L668)
  does not check that the `batch_dims` value that the user supplies is less than the
  rank of the input tensor. Since the implementation uses several for loops over the
  dimensions of `tensor`, this results in reading data from outside the bounds of
  heap allocated buffer backing the tensor. We have patched the issue in GitHub commit
  bc9c546ce7015c57c2f15c168b3d9201de679a1d. The fix will be included in TensorFlow
  2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3,
  and TensorFlow 2.3.4, as these are also affected and still in supported range.
affects:
  ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    fixed: bc9c546ce7015c57c2f15c168b3d9201de679a1d
  - type: ECOSYSTEM
    introduced: 2.3.0
    fixed: 2.3.4
  - type: ECOSYSTEM
    introduced: 2.4.0
    fixed: 2.4.3
references:
- type: WEB
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-2r8p-fg3c-wcj4
- type: WEB
  url: https://github.com/tensorflow/tensorflow/commit/bc9c546ce7015c57c2f15c168b3d9201de679a1d
aliases:
- CVE-2021-37654
modified: "2021-08-18T14:30:00Z"
published: "2021-08-12T21:15:00Z"
