id: PYSEC-0000-CVE-2015-3206
package:
  name: pykerberos
  ecosystem: PyPI
details: The checkPassword function in python-kerberos does not authenticate the KDC
  it attempts to communicate with, which allows remote attackers to cause a denial
  of service (bad response), or have other unspecified impact by performing a man-in-the-middle
  attack.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 1.1.6
references:
- type: WEB
  url: https://pypi.python.org/pypi/kerberos
- type: WEB
  url: https://github.com/apple/ccs-pykerberos/issues/31
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1223802
- type: WEB
  url: http://www.securityfocus.com/bid/74760
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2015/05/21/3
aliases:
- CVE-2015-3206
modified: "2018-12-20T18:11:00Z"
published: "2017-08-25T18:29:00Z"
